test(store): add more codegen tests [M-01]
latticexyz/mud pull request #2176
Opened 2024-01-23 12:52 UTC by holic

2024-01-23 17:38 UTC, yonadaaa requested changes
Overall good, just I think we should be testing more events beyond `helloStoreEvent`, but maybe I missed that change

2024-01-23 17:38 UTC, yonadaaa commented on packages/store/ts/storeEvents.test.ts
Should we add tests to cover more events than just `HelloStore`?

2024-01-23 17:38 UTC, yonadaaa commented on packages/store/test/constants.t.sol
Random thought: is it possible to implement this logic in TS (avoiding FFI) and read the constants from the Solidity files somehow?

2024-01-23 17:39 UTC, yonadaaa commented on packages/store/ts/storeEvents.test.ts
Oh, I see now. Were we already testing this, so you just moved the test from `storeEventsAbi.test.ts`?

2024-01-24 09:50 UTC, holic commented on packages/store/ts/storeEvents.test.ts
yep! I added the store events test to `storeEvents.test.ts` then found that it was essentially duplicating `storeEventsAbi.test.ts` so I removed it (which OZ also recommended)

2024-01-24 09:51 UTC, holic commented on packages/store/test/constants.t.sol
That was my initial thought/path but I didn't want to introduce the Solidity parser into this package. We were using the `vm.ffi` approach elsewhere already so I borrowed that:
https://github.com/latticexyz/mud/blob/main/packages/world/test/CoreModule.t.sol#L58-L71

2024-01-24 10:55 UTC, merged