automatically convert ASCII salt to hex
latticexyz/mud pull request #3257
Opened 2024-10-05 19:37 UTC by AyushSagar99

2024-10-05 21:45 UTC, alvrs requested changes

2024-10-05 21:45 UTC, alvrs commented on packages/cli/src/runDeploy.ts
> +    in your contracts directory to use the default anvil private key.`,
let's not change the formatting here

2024-10-05 21:45 UTC, alvrs commented on packages/cli/src/runDeploy.ts
> -      // a consistent address but different block number, we'll ignore the block number.
let's keep all these comments

2024-10-05 21:45 UTC, alvrs commented on packages/cli/src/runDeploy.ts
> +
there is a util from `viem` we can use instead: https://viem.sh/docs/utilities/toHex.html

2024-10-05 21:45 UTC, alvrs commented on packages/cli/src/runDeploy.ts
> +    salt, // Use the new salt variable here
no need to add a comment here

2024-10-05 21:45 UTC, alvrs commented on packages/cli/src/runDeploy.ts
> +    }
we can simplify this to `const salt = opts.salt && !isHex(opts.salt) ? toHex(opts.salt) : opts.salt;`

2024-10-06 10:56 UTC, holic commented on packages/cli/src/runDeploy.ts
> - */
why were these comments removed?

2024-10-18 15:02 UTC, holic commented
@AyushSagar99 just checking if you plan to finish up this PR or not!

2024-10-19 13:54 UTC, AyushSagar99 commented
@holic yes i would finish but i am encountering some problem and want to ask some questions is their a way we can connect

2024-10-19 16:43 UTC, holic commented
we're always on discord in the #mud-help channel: https://lattice.xyz/discord

2025-01-09 10:49 UTC, closed without merging