docs: libs in deploy.json
latticexyz/mud pull request #364
Opened 2023-02-02 19:43 UTC by dk1a

For #361

2023-02-02 19:49 UTC, holic requested changes

2023-02-02 19:49 UTC, holic commented on guides/getting_started.md
> +Libs should be in the `libraries` directory.
We should probably add more context to answer the "why" behind this: what is this useful for?

2023-02-02 19:49 UTC, holic commented on guides/getting_started.md
> +  "libs": [{ "name": "LibInitData", "func": "init" }]
It'd be nice to change `libs` to `libraries` to match the directory name (and the verbosity of `components` and `systems`) above. And maybe `func` -> `function` or just ~always default to `init` and make it not configurable?

Another thought is an `initializers` key to make it clear what they're for:
```json
{
  "initializers": ["LibInitData"]
}
```

2023-02-02 20:04 UTC, dk1a commented
I like `initializers`, changed it up, and with the new name it seems self-descriptive too

2023-02-02 20:14 UTC, holic approved these changes
👏  Looks great, thank you!

My only other curiosity now is in terms of `mud dev` and "hot reloading" of contracts, when do initializers run? Once only on initial world deploy? On every change to the initializer lib?

2023-02-02 20:20 UTC, dk1a commented
> My only other curiosity now is in terms of mud dev and "hot reloading" of contracts, when do initializers run? Once only on initial world deploy? On every change to the initializer lib?

Good point, I use hsr too rarely to have thought of this. I made initializers respect the `init` flag, but it's kinda useless, especially for hot reloading. I think I should move inits from `deploySystems` into `deploy` and use `_reuseComponents`, so initializers run only if components are redeployed

2023-02-02 20:24 UTC, holic commented
cc @alvrs for input

2023-02-02 20:25 UTC, dk1a commented
Oh, and to be more specific, hsr always reuses components afaik, so `deploy-contracts --watch` will ignore any changes to components and initializers, and only update the system code

2023-02-02 20:48 UTC, dk1a commented
> Oh, and to be more specific, hsr always reuses components afaik, so deploy-contracts --watch will ignore any changes to components and initializers, and only update the system code

After some testing turns out `deploy-contracts --watch` always had `reuseComponents: false`, which means it just didn't work? Since components can never be redeployed (#286).
I fixed it and everything seems to work as I expect and think it should (as in, `deploy-contracts --watch` deploys everything and runs initializers once, and on any change only redeploys the systems).

@alvrs I may be missing something, check out the changes to see if they make sense and the bug really existed

2023-02-02 22:41 UTC, alvrs commented on guides/getting_started.md
> +`initializers` are optional libraries. After components and systems are deployed, `init` function of each initializer will be called with `IWorld` as the sole argument, e.g. `LibInitData.init(world)`
```suggestion
The `initializers` field in the `deploy.json` file allows the specification of libraries that implement a function named `init` which takes a single argument `IWorld`. This `init` function is executed after the deployment of the world, components, and systems, as part of the deployment process (e.g. `LibInitData.init(world)`).
```

2023-02-02 22:43 UTC, alvrs commented
> After some testing turns out deploy-contracts --watch always had reuseComponents: false, which means it just didn't work?

Good catch! Previously we set `reuseComponents` to `true` when specific systems were provided, but this was recently changed in https://github.com/latticexyz/mud/pull/356/files and the implications for HMR missed. Thanks for fixing!

2023-02-03 12:08 UTC, alvrs approved these changes

2023-02-03 12:09 UTC, merged