Ensure transactions are submitted at eip-1559
latticexyz/mud pull request #465
Opened 2023-03-07 14:41 UTC by 0xhank

Problem was manually setting gasPrice in `createTxQueue` was forcing transactions to be submitted as legacy type, because you can't submit an eip1559 while overriding gasPrice.

This update instead sets the value of `maxPriorityFeePerGas` and `maxFeePerGas` which are the proper ways to set gas price using eip1559 anyway.

2023-03-07 14:53 UTC, ludns requested changes
see comment above

2023-03-15 14:59 UTC, dk1a commented
based on my similar experience with lattice testnet using
```solidity
maxPriorityFeePerGas: gasPrice$.getValue() * 2,
maxFeePerGas: gasPrice$.getValue() * 4,
```
was not enough, and I had to hardcode actual numbers instead of `gasPrice$.getValue()`. Haven't looked into the specifics, but there might be something wrong with `gasPrice$`

2023-03-15 16:35 UTC, ludns commented
Gas price from the node is incorrect for some reason, and it's generally not recommended to turn gas price into base fee.
I would look at the `deploy-v2` script in the CLI for a robust way to fetch the latest baseFee and  bump it up using ethers [getFeeData](https://docs.ethers.org/v5/api/providers/provider/#Provider-getFeeData)

2023-06-12 17:21 UTC, alvrs commented
Closing this for now as it's only relevant for v1 and our focus is on getting v2 stable. Happy to merge a PR to the [`v1`](https://github.com/latticexyz/mud/tree/v1) branch if a contributor wants to pick it up.

2023-06-12 17:21 UTC, closed without merging